### ISSUE TITLE
Crash in processInlineRanges

### ISSUE THREAD

**Issue by hartbit** [krzysztofzablocki/Sourcery#156]
I can't reproduce it easily but here goes:

```
2017-02-14 14:00:48.555 sourcery[9930:476176] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString replaceCharactersInRange:withString:]: Range or index out of bounds'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9a1fc37b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffaf208c9d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9a27ac3d +[NSException raise:format:] + 205
	3   CoreFoundation                      0x00007fff9a22c3a5 mutateError + 261
	4   Foundation                          0x00007fff9bc440a3 -[NSString stringByReplacingCharactersInRange:withString:] + 142
	5   sourcery                            0x00000001005b24cd _TFFFC8sourcery8SourceryP33_F83099E77BBE10FEADF33BF7571993A819processInlineRangesFzT3forT5typesGSaCS_4Type_12inlineRangesGSaT4fileSS6rangesGVs10DictionarySSVSC8_NSRange____2inSS_SSU1_FzTSSS3__T_U_FzTSSGS2_SSS3___T_ + 749
	6   sourcery                            0x00000001005b2ab6 _TPA__TFFFC8sourcery8SourceryP33_F83099E77BBE10FEADF33BF7571993A819processInlineRangesFzT3forT5typesGSaCS_4Type_12inlineRangesGSaT4fileSS6rangesGVs10DictionarySSVSC8_NSRange____2inSS_SSU1_FzTSSS3__T_U_FzTSSGS2_SSS3___T_ + 214
	7   sourcery                            0x00000001005b27dd _TTRXFo_oSSoGVs10DictionarySSVSC8_NSRange__zoPs5Error__XFo_iT4fileSS6rangesGS_SSS0____zoPS1___ + 77
	8   libswiftCore.dylib                  0x0000000100c24dd5 _TFEsPs8Sequence7forEachfzFzWx8Iterator7Element_T_T_ + 389
	9   sourcery                            0x00000001005b1f8b _TFFC8sourcery8SourceryP33_F83099E77BBE10FEADF33BF7571993A819processInlineRangesFzT3forT5typesGSaCS_4Type_12inlineRangesGSaT4fileSS6rangesGVs10DictionarySSVSC8_NSRange____2inSS_SSU1_FzTSSS3__T_ + 603
	10  sourcery                            0x00000001005b21cb _TPA__TFFC8sourcery8SourceryP33_F83099E77BBE10FEADF33BF7571993A819processInlineRangesFzT3forT5typesGSaCS_4Type_12inlineRangesGSaT4fileSS6rangesGVs10DictionarySSVSC8_NSRange____2inSS_SSU1_FzTSSS3__T_ + 235
	11  sourcery                            0x00000001005b2875 _TTRXFo_oSSdVSC8_NSRange_zoPs5Error__XFo_iTSSS___zoPS0___ + 85
	12  libswiftCore.dylib                  0x0000000100c24dd5 _TFEsPs8Sequence7forEachfzFzWx8Iterator7Element_T_T_ + 389
	13  sourcery                            0x00000001005b07b8 _TFC8sourcery8SourceryP33_F83099E77BBE10FEADF33BF7571993A819processInlineRangesfzT3forT5typesGSaCS_4Type_12inlineRangesGSaT4fileSS6rangesGVs10DictionarySSVSC8_NSRange____2inSS_SS + 888
	14  sourcery                            0x00000001005af47b _TFC8sourcery8SourceryP33_F83099E77BBE10FEADF33BF7571993A88generatefzTPS_8Template_16forParsingResultT5typesGSaCS_4Type_12inlineRangesGSaT4fileSS6rangesGVs10DictionarySSVSC8_NSRange_____SS + 1707
	15  sourcery                            0x00000001005aff90 _TFFC8sourcery8SourceryP33_F83099E77BBE10FEADF33BF7571993A88generateFzT12templatePathV7PathKit4Path6outputS2_13parsingResultT5typesGSaCS_4Type_12inlineRangesGSaT4fileSS6rangesGVs10DictionarySSVSC8_NSRange_____T_U0_FzPS_8Template_T_ + 288
	16  sourcery                            0x00000001005b0433 _TPA__TFFC8sourcery8SourceryP33_F83099E77BBE10FEADF33BF7571993A88generateFzT12templatePathV7PathKit4Path6outputS2_13parsingResultT5typesGSaCS_4Type_12inlineRangesGSaT4fileSS6rangesGVs10DictionarySSVSC8_NSRange_____T_U0_FzPS_8Template_T_ + 179
	17  libswiftCore.dylib                  0x0000000100c24dd5 _TFEsPs8Sequence7forEachfzFzWx8Iterator7Element_T_T_ + 389
	18  sourcery                            0x00000001005a83ca _TFC8sourcery8SourceryP33_F83099E77BBE10FEADF33BF7571993A88generatefzT12templatePathV7PathKit4Path6outputS2_13parsingResultT5typesGSaCS_4Type_12inlineRangesGSaT4fileSS6rangesGVs10DictionarySSVSC8_NSRange_____T_ + 1354
	19  sourcery                            0x00000001005a8f23 _TFFC8sourcery8Sourcery12processFilesFzTV7PathKit4Path14usingTemplatesS2_6outputS2__GSqGSaCOS_13FolderWatcher5Local__U_FGSaVS3_5Event_T_ + 1699
	20  sourcery                            0x00000001005aa818 _TPA__TFFC8sourcery8Sourcery12processFilesFzTV7PathKit4Path14usingTemplatesS2_6outputS2__GSqGSaCOS_13FolderWatcher5Local__U_FGSaVS3_5Event_T_ + 248
	21  sourcery                            0x000000010063b264 _TFFCO8sourcery13FolderWatcher5LocalcFT4pathSS7latencySd7closureFGSaVS0_5Event_T__S1_L_7handlerFTVs13OpaquePointer18clientCallbackInfoGSqSv_9numEventsSi10eventPathsSv10eventFlagsGSqGSPVs6UInt32__8eventIDsGSqGSPVs6UInt64___T_ + 980
	22  sourcery                            0x000000010063b8d9 _TToFFCO8sourcery13FolderWatcher5LocalcFT4pathSS7latencySd7closureFGSaVS0_5Event_T__S1_L_7handlerFTVs13OpaquePointer18clientCallbackInfoGSqSv_9numEventsSi10eventPathsSv10eventFlagsGSqGSPVs6UInt32__8eventIDsGSqGSPVs6UInt64___T_ + 9
	23  FSEvents                            0x00007fff9b368af3 implementation_callback_rpc + 1883
	24  FSEvents                            0x00007fff9b3666fe _Xcallback_rpc + 254
	25  FSEvents                            0x00007fff9b3667bc FSEventsD2F_server + 55
	26  FSEvents                            0x00007fff9b36bfdd FSEventsClientProcessMessageCallback + 44
	27  CoreFoundation                      0x00007fff9a17b29d __CFMachPortPerform + 253
	28  CoreFoundation                      0x00007fff9a17b189 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	29  CoreFoundation                      0x00007fff9a17b101 __CFRunLoopDoSource1 + 465
	30  CoreFoundation                      0x00007fff9a172d75 __CFRunLoopRun + 2389
	31  CoreFoundation                      0x00007fff9a1721c4 CFRunLoopRunSpecific + 420
	32  Foundation                          0x00007fff9bbd63c2 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 277
	33  Foundation                          0x00007fff9bbd629a -[NSRunLoop(NSRunLoop) run] + 76
	34  sourcery                            0x00000001005a4424 _TFF8sourcery6runCLIFT_T_U_FTSbSbSbV7PathKit4PathS1_S1_VS_15CustomArguments_T_ + 788
	35  sourcery                            0x00000001005a486c _TTRXFo_dSbdSbdSboV7PathKit4PathoS0_oS0_oV8sourcery15CustomArguments_zoPs5Error__XFo_iSbiSbiSbiS0_iS0_iS0_iS2__zoPS3___ + 188
	36  sourcery                            0x00000001005a51ce _TPA__TTRXFo_dSbdSbdSboV7PathKit4PathoS0_oS0_oV8sourcery15CustomArguments_zoPs5Error__XFo_iSbiSbiSbiS0_iS0_iS0_iS2__zoPS3___ + 158
	37  sourcery                            0x00000001006fee2c _TFF9Commander7commandu5_RxS_18ArgumentDescriptor_S0_0_S0_1_S0_2_S0_3_S0_4_S0_rFTxq_q0_q1_q2_q3_q4_FzTwx9ValueTypew_S1_w0_S1_w1_S1_w2_S1_w3_S1_w4_S1__T__PS_11CommandType_U_FzCS_14ArgumentParserT_ + 4028
	38  sourcery                            0x00000001006ffa5d _TPA__TFF9Commander7commandu5_RxS_18ArgumentDescriptor_S0_0_S0_1_S0_2_S0_3_S0_4_S0_rFTxq_q0_q1_q2_q3_q4_FzTwx9ValueTypew_S1_w0_S1_w1_S1_w2_S1_w3_S1_w4_S1__T__PS_11CommandType_U_FzCS_14ArgumentParserT_ + 717
	39  sourcery                            0x00000001006e4902 _TFV9Commander16AnonymousCommand3runfzCS_14ArgumentParserT_ + 82
	40  sourcery                            0x00000001006e4a44 _TTWV9Commander16AnonymousCommandS_11CommandTypeS_FS1_3runfzCS_14ArgumentParserT_ + 68
	41  sourcery                            0x00000001006e5895 _TFE9CommanderPS_11CommandType3runfGSqSS_Os5Never + 1109
	42  sourcery                            0x00000001005a4029 _TF8sourcery6runCLIFT_T_ + 3289
	43  sourcery                            0x00000001005a26e3 main + 307
	44  libdyld.dylib                       0x00007fffafaeb235 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by krzysztofzablocki** [comment]
does it happen only with watcher mode?

**Comment by hartbit** [comment]
I've only been using watcher mode. So can't tell you yet if it happens with "standard" mode.

**Comment by cocoahero** [comment]
Seeing the same error. We're using Sourcery in an Xcode Build Phase, so not using watcher.

```
2017-02-15 14:19:59.069 Sourcery[83260:4307583] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString replaceCharactersInRange:withString:]: Range or index out of bounds'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffacc41e7b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffc182bcad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffaccc099d +[NSException raise:format:] + 205
	3   CoreFoundation                      0x00007fffacc71d35 mutateError + 261
	4   Foundation                          0x00007fffae63a293 -[NSString stringByReplacingCharactersInRange:withString:] + 142
	5   Sourcery                            0x000000010c6a6a58 _TTSf4gs_g_gs_gs_d___TFFFC8Sourcery8SourceryP33_DB5C4364BFA94633EE953DD412A08C3019processInlineRangesFzT3forT5typesGSaCS_4Type_12inlineRangesGSaT4fileSS6rangesGVs10DictionarySSVSC8_NSRange____2inSS_SSU1_FzTSSS3__T_U_FzTSSGS2_SSS3___T_ + 1016
	6   Sourcery                            0x000000010c6a7c07 _TTSf4n_n_g_n___TFC8Sourcery8SourceryP33_DB5C4364BFA94633EE953DD412A08C308generatefzTPS_8Template_16forParsingResultT5typesGSaCS_4Type_12inlineRangesGSaT4fileSS6rangesGVs10DictionarySSVSC8_NSRange_____SS + 3799
	7   Sourcery                            0x000000010c6a8c5e _TTSf4gs_gs_n_g_n___TFC8Sourcery8SourceryP33_DB5C4364BFA94633EE953DD412A08C308generatefzT12templatePathV7PathKit4Path6outputS2_13parsingResultT5typesGSaCS_4Type_12inlineRangesGSaT4fileSS6rangesGVs10DictionarySSVSC8_NSRange_____T_ + 1790
	8   Sourcery                            0x000000010c6a94ae _TTSf4gs_gs_s_n___TFC8Sourcery8Sourcery12processFilesfzTV7PathKit4Path14usingTemplatesS2_6outputS2__GSqGSaCOS_13FolderWatcher5Local__ + 398
	9   Sourcery                            0x000000010c6500d1 _TTSf4n_n_n_gs_gs_gs_g___TFF8Sourcery6runCLIFT_T_U_FTSbSbSbV7PathKit4PathS1_S1_VS_15CustomArguments_T_ + 449
	10  Sourcery                            0x000000010c64c448 _TFF8Sourcery6runCLIFT_T_U_FTSbSbSbV7PathKit4PathS1_S1_VS_15CustomArguments_T_ + 88
	11  Sourcery                            0x000000010c655fc0 _TPA__TTRXFo_dSbdSbdSboV7PathKit4PathoS0_oS0_oV8Sourcery15CustomArguments_zoPs5Error__XFo_iSbiSbiSbiS0_iS0_iS0_iS2__zoPS3___ + 192
	12  Commander                           0x000000010c843ad8 _TFF9Commander7commandu5_RxS_18ArgumentDescriptor_S0_0_S0_1_S0_2_S0_3_S0_4_S0_rFTxq_q0_q1_q2_q3_q4_FzTwx9ValueTypew_S1_w0_S1_w1_S1_w2_S1_w3_S1_w4_S1__T__PS_11CommandType_U_FzCS_14ArgumentParserT_ + 2952
	13  Commander                           0x000000010c84431d _TPA__TFF9Commander7commandu5_RxS_18ArgumentDescriptor_S0_0_S0_1_S0_2_S0_3_S0_4_S0_rFTxq_q0_q1_q2_q3_q4_FzTwx9ValueTypew_S1_w0_S1_w1_S1_w2_S1_w3_S1_w4_S1__T__PS_11CommandType_U_FzCS_14ArgumentParserT_ + 605
	14  Commander                           0x000000010c83411f _TFE9CommanderPS_11CommandType3runfGSqSS_Os5Never + 287
	15  Sourcery                            0x000000010c64c3e7 _TF8Sourcery6runCLIFT_T_ + 1943
	16  Sourcery                            0x000000010c64b7b1 main + 241
	17  libdyld.dylib                       0x00007fffc210f255 start + 1
	18  ???                                 0x0000000000000004 0x0 + 4
)
```

**Comment by krzysztofzablocki** [comment]
Are you guys using the inline feature at all? I'll be taking a look at this soon

**Comment by hartbit** [comment]
I am using the inline feature

**Comment by cocoahero** [comment]
Yup, using the inline feature.

**Comment by krzysztofzablocki** [comment]
@cocoahero @hartbit can you try `0.5.6` I just released? there was one bug that might have affected this logic

**Comment by hartbit** [comment]
I can only test Monday.

**Comment by krzysztofzablocki** [comment]
any updates @hartbit @cocoahero ?

**Comment by hartbit** [comment]
@krzysztofzablocki I still have some crashes but not the same. The ones I have now don't have a stack trace :(

**Comment by krzysztofzablocki** [comment]
@hartbit on `0.5.7`?

**Comment by hartbit** [comment]
Yes. The funny thing is if I run the command again without changing anything, it goes through. Very random.

**Comment by hartbit** [comment]
```
$ .build/debug/sourcery Mimosa Templates Mimosa/Generated
Scanning sources...
[1]    68504 segmentation fault  .build/debug/sourcery Mimosa Templates Mimosa/Generated
$ .build/debug/sourcery Mimosa Templates Mimosa/Generated
Scanning sources...
Found 237 types.
Loading templates...
Loaded 3 templates.
Generating code...
Finished.
Processing time 0.302587032318115 seconds
```

**Comment by krzysztofzablocki** [comment]
ok, we will need to add more verbose logging to track it down
