### ISSUE TITLE
NSCocoaErrorDomain Code=4

### ISSUE THREAD

**Issue by maxmamis** [krzysztofzablocki/Sourcery#745]
I'm seeing an error whenever I try to generate files using Sourcery. The error looks like this:

```
error: Error Domain=NSCocoaErrorDomain Code=4 "“SwiftTemplate” couldn’t be moved to “Mock.swifttemplate” because either the former doesn’t exist, or the folder containing the latter doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/var/folders/4s/kz_7_74j6y9dgr4zv1zty5w40000gn/T/SwiftTemplate/0.16.0/.build/debug/SwiftTemplate, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Users/max/Library/Caches/Sourcery/Mock.swifttemplate/68oTZ5uoc%2FNLqYRTuvHnzYxhRGfxDXdvwT7dDod7lWc%3D, NSFilePath=/var/folders/4s/kz_7_74j6y9dgr4zv1zty5w40000gn/T/SwiftTemplate/0.16.0/.build/debug/SwiftTemplate, NSUnderlyingError=0x7f80c04e5800 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

I'm seeing this error on Sourcery 0.16.0 as well as on the latest master branch. (I built the latter with Xcode 10.2). Running Mojave 10.14.4.

I see two other issues that look like they're related, but both were closed without an apparent resolution. The suggestion to clean the `~/Library/Caches/Sourcery` folder did not work for me.

Related issues:
https://github.com/krzysztofzablocki/Sourcery/issues/739
https://github.com/krzysztofzablocki/Sourcery/issues/741

It also appears this PR (https://github.com/krzysztofzablocki/Sourcery/pull/744) was meant to fix the issue, but again I'm still seeing it on the latest master.

**Comment by krzysztofzablocki** [comment]
@Liquidsoul ideas?

**Comment by Liquidsoul** [comment]
We need more information to figure this one out.
@maxmamis Could you please answer the reason of the error ?
> either the former doesn’t exist, or the folder containing the latter doesn’t exist

I mean telling us which parts of these paths are present on disk:
- `/Users/max/Library/Caches/Sourcery/Mock.swifttemplate/68oTZ5uoc%2FNLqYRTuvHnzYxhRGfxDXdvwT7dDod7lWc%3D`
- `/var/folders/4s/kz_7_74j6y9dgr4zv1zty5w40000gn/T/SwiftTemplate/0.16.0/.build/debug/SwiftTemplate`

Also, could you check if running Sourcery with the cache disabled (with `--disableCache`) produce the same error?

**Comment by maxmamis** [comment]
@Liquidsoul When I run with `--disableCache` I get a different error:

```
2019-04-02 11:57:55.460 Sourcery[37914:1921903] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'launch path not accessible'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff53624cf9 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7e1b9a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff53624b2b +[NSException raise:format:] + 201
	3   Foundation                          0x00007fff5580a99f -[NSConcreteTask launchWithDictionary:error:] + 1291
	4   SourcerySwift                       0x0000000103981342 $sSo6NSTaskC13SourcerySwiftE10runCommand33_97A733547C26B01DA3FEDC2EDE49AED9LL4path9arguments11environment20currentDirectoryPathAC13ProcessResultAELLVSS_SaySSGSDyS2SG0R3Kit0R0VSgtKFZTf4xnnnd_n + 1922
	5   SourcerySwift                       0x000000010397a8c3 $s13SourcerySwift0B8TemplateC6renderySSypKF + 1331
	6   Sourcery                            0x000000010317abfa $s13SourcerySwift0B8TemplateC0A9Framework0C00A0AdEP6renderySS0A7Runtime0C7ContextCKFTW + 74
	7   SourceryFramework                   0x0000000103b4240a $s17SourceryFramework9GeneratorO8generate_8template9argumentsSS0A7Runtime5TypesC_AA8Template_pSDySSSo8NSObjectCGtKFZ + 426
	8   Sourcery                            0x000000010316587f $s8SourceryAAC8generate33_DB5C4364BFA94633EE953DD412A08C30LL_16forParsingResult10outputPathSS0A9Framework8Template_p_0A7Runtime5TypesC5types_SaySS4file_SDySSSo8_NSRangeVG6rangesSDyS2SG12indentationstG12inlineRangest0N3Kit0N0VtKF + 1103
	9   Sourcery                            0x0000000103175f95 $s8SourceryAAC8generate33_DB5C4364BFA94633EE953DD412A08C30LL6source13templatePaths6output13parsingResultyAA6SourceO_AA0L0VAA6OutputV0A7Runtime5TypesC5types_SaySS4file_SDySSSo8_NSRangeVG6rangesSDyS2SG12indentationstG12inlineRangesttKFTf4dxnnnn_n + 1541
	10  Sourcery                            0x0000000103177808 $s8SourceryAAC12processFiles_14usingTemplates6output10forceParseSayAA13FolderWatcherO5LocalCGSgAA6SourceO_AA5PathsVAA6OutputVSaySSGtKF0A7Runtime5TypesC5types_SaySS4file_SDySSSo8_NSRangeVG6rangesSDyS2SG12indentationstG12inlineRangestANKcfU1_Tf4nnnxn_n + 3688
	11  Sourcery                            0x000000010317830a $s8SourceryAAC12processFiles_14usingTemplates6output10forceParseSayAA13FolderWatcherO5LocalCGSgAA6SourceO_AA5PathsVAA6OutputVSaySSGtKFTf4nxnnn_n + 1898
	12  Sourcery                            0x000000010314fd49 $s8Sourcery6runCLIyyFySb_S4bSay7PathKit0D0VGA3f2ESaySSGAgEtcfU_ + 2441
	13  Sourcery                            0x0000000103150210 $sS5bSay7PathKit0A0VGA3d2CSaySSGAeCs5Error_pIegyyyyyggggnnggnzo_S5bA4d2c2eCsAF_pIegnnnnnnnnnnnnnnzo_TR032$s8Sourcery6runCLIyyFySb_S4bSay7A27Kit0D0VGA3f2ESaySSGAgEtcfU_Tf3nnnnnnnnnnnnnnpf_n + 80
	14  Commander                           0x0000000103254b54 $s9Commander7commandyAA11CommandType_px_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_y05ValueD0Qz_ADQy_ADQy0_ADQy1_ADQy2_ADQy3_ADQy4_ADQy5_ADQy6_ADQy7_ADQy8_ADQy9_ADQy10_ADQy11_tKctAA18ArgumentDescriptorRzAaSR_AaSR0_AaSR1_AaSR2_AaSR3_AaSR4_AaSR5_AaSR6_AaSR7_AaSR8_AaSR9_AaSR10_AaSR11_r12_lFyAA0F6ParserCKcfU_ + 5204
	15  Commander                           0x0000000103254d77 $s9Commander7commandyAA11CommandType_px_q_q0_q1_q2_q3_q4_q5_q6_q7_q8_q9_q10_q11_y05ValueD0Qz_ADQy_ADQy0_ADQy1_ADQy2_ADQy3_ADQy4_ADQy5_ADQy6_ADQy7_ADQy8_ADQy9_ADQy10_ADQy11_tKctAA18ArgumentDescriptorRzAaSR_AaSR0_AaSR1_AaSR2_AaSR3_AaSR4_AaSR5_AaSR6_AaSR7_AaSR8_AaSR9_AaSR10_AaSR11_r12_lFyAA0F6ParserCKcfU_TA + 279
	16  Commander                           0x0000000103241193 $s9Commander16AnonymousCommandVAA0C4TypeA2aDP3runyyAA14ArgumentParserCKFTW + 51
	17  Commander                           0x00000001032415a9 $s9Commander11CommandTypePAAE3runys5NeverOSSSgF + 345
	18  Sourcery                            0x000000010314f3bb $s8Sourcery6runCLIyyF + 2523
	19  Sourcery                            0x000000010314de54 main + 84
	20  libdyld.dylib                       0x00007fff7f9e73d5 start + 1
	21  ???                                 0x0000000000000004 0x0 + 4
)
```

As for the paths from the original command — they are _both_ missing! 

• /Users/max/Library/Caches/Sourcery/Mock.swifttemplate is an empty directory
• /var/folders/4s/kz_7_74j6y9dgr4zv1zty5w40000gn/T/SwiftTemplate/0.16.0/.build/debug is an empty directory

**Comment by maxmamis** [comment]
If it helps with the `--disableCache` error, the full command I'm running is:

`/Users/max/Library/Developer/Xcode/DerivedData/Sourcery-erknevrxmtxsfhdgcykxcngqqfnu/Build/Products/Release/Sourcery.app/Contents/MacOS/Sourcery --config mocky.yml --disableCache`

still running Sourcery on the latest master.

**Comment by 6h4k5h498h9485gh39458h9o12um3412j34lj** [comment]
Cleaning ` ~/Library/Caches/Sourcery` doesn't help.
If I do `--disableCache` I just don't get any generated _.swift_-files.

**macOS 10.14.3**
**Xcode 10.2**
```
Error Domain=NSCocoaErrorDomain Code=4 "“SwiftTemplate” couldn’t be moved to “ParsingChecks.swifttemplate” because either the former doesn’t exist, or the folder containing the latter doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/var/folders/qf/72hdm5lj075ctxsqcl1ffmqc0000gn/T/SwiftTemplate/0.16.0/.build/debug/SwiftTemplate, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Users/ivangoremykin/Library/Caches/Sourcery/ParsingChecks.swifttemplate/41rImoJ4WlvVA0zxl0uvemh%2FT4NWUy9oPo1fQiYJJmY%3D, NSFilePath=/var/folders/qf/72hdm5lj075ctxsqcl1ffmqc0000gn/T/SwiftTemplate/0.16.0/.build/debug/SwiftTemplate, NSUnderlyingError=0x7fc33dcb1450 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Comment by amichnia** [comment]
@maxmamis If you are using older SwiftyMocky with Sourcery 0.16.0, there is an issue with `arguments` being renamed to `argument`. I was getting similar errors. So I bet in other cases it could be also related with that rename.

I've just released SwiftyMocky 3.2.0, that works on Sourcery 0.16.0, both Swift 4.2 and 5.0. Should fix it.

**Comment by maxmamis** [comment]
@amichnia I was using 3.2.0-pre, I'll update to 3.2.0 to see if that helps. It _did_ appear to me as that the codegen was succeeding, and the error happened when trying to write the file (or some other step in the process). Might as well give it a shot though :)

**Comment by maxmamis** [comment]
@amichnia SwiftyMocky 3.2.0 did in fact solve my problem, thanks! 💯

**Comment by 6h4k5h498h9485gh39458h9o12um3412j34lj** [comment]
Hey, @maxmamis, other folks including myself don't use SwiftyMocky and we still have this issue unsolved.
@krzysztofzablocki asked to keep the discussion in this ticket.
Please reopen it.

**Comment by maxmamis** [comment]
@6h4k5h498h9485gh39458h9o12um3412j34lj reopened! Sorry about that, didn't realize others were interested

**Comment by amichnia** [comment]
@6h4k5h498h9485gh39458h9o12um3412j34lj 
Ok, but isn't the problem kind of the same? Not sure what templates do you use, but the first thing I would do is checking the swifttemplate for "arguments" and rename it to "argument".

**Comment by krzysztofzablocki** [comment]
@6h4k5h498h9485gh39458h9o12um3412j34lj yeah can you check if the template doesn't have that old `arguments` name?

**Comment by 6h4k5h498h9485gh39458h9o12um3412j34lj** [comment]
@krzysztofzablocki I just don't have this «argument» section in the _.yml_-file:
```
sources:
  - ../../Source
templates:
  - ../Templates/Parsing
output:
  ../../Source/Generated
```

**Comment by amichnia** [comment]
@6h4k5h498h9485gh39458h9o12um3412j34lj 

It's not about `.yml` config file, check all the templates in ../Templates/Parsing

The case is, that templates (for sure `.swifttemplate` files) were using `arguments` provided by Sourcery. It got renamed to `argument`, so a lot of templates become invalid.

**Comment by 6h4k5h498h9485gh39458h9o12um3412j34lj** [comment]
@amichnia Yes I've checked those  `.swifttemplate` files, but unfortunately my problem is not caused by the `arguments` → `argument` renaming.

**Comment by 6h4k5h498h9485gh39458h9o12um3412j34lj** [comment]
@krzysztofzablocki @amichnia I think I have found the cause.
It has something to do with includes: `<%- include("ParsingCommon.swifttemplate") -%>`

I have already described this issue in #729.

In Sourcery 0.15.0 I couldn't have a «diamond» include situation, so I got rid of it and duplicated my code instead of sharing it in a separate file and including it in other 2 other templates.

I haven't removed this shared `.swifttemplate` file though.
In my `.yml` I specify
```
templates:
  - ../Templates/Parsing
```

This shared `.swifttemplate` doesn't output to any `.swift` file, it only contains shared code.
Sourcery 0.15.0 was ok with it.
Sourcery 0.16.0 wasn't:
```
Error Domain=NSCocoaErrorDomain Code=4 "“SwiftTemplate” couldn’t be moved to “ParsingChecks.swifttemplate” because either the former doesn’t exist, or the folder containing the latter doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/var/folders/qf/72hdm5lj075ctxsqcl1ffmqc0000gn/T/SwiftTemplate/0.16.0/.build/debug/SwiftTemplate, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Users/ivangoremykin/Library/Caches/Sourcery/ParsingChecks.swifttemplate/41rImoJ4WlvVA0zxl0uvemh%2FT4NWUy9oPo1fQiYJJmY%3D, NSFilePath=/var/folders/qf/72hdm5lj075ctxsqcl1ffmqc0000gn/T/SwiftTemplate/0.16.0/.build/debug/SwiftTemplate, NSUnderlyingError=0x7fc33dcb1450 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

I have changed my configuration to ignore those shared templates  and it all works now:
```
templates:
  - ../Templates/Parsing/Parser.swifttemplate
```

**Comment by 6h4k5h498h9485gh39458h9o12um3412j34lj** [comment]
@krzysztofzablocki We would appreciate a versatile approach to includes in Swift Templates since you can't have a modular template architecture without it.

You will just end up with a single template file per issue (like `JsonParsing.swifttemplate`, `RealmLocalStorage.swifttemplate`, `WebServiceTesting.swifttemplate`, etc.) and _lots_ of code duplication in them.

**Comment by krzysztofzablocki** [comment]
@6h4k5h498h9485gh39458h9o12um3412j34lj any chance you could create a minimal sample project that reproduces this issue so we can easily reproduce to try to figure out whats wrong?

**Comment by 6h4k5h498h9485gh39458h9o12um3412j34lj** [comment]
@krzysztofzablocki sure, give me a day.

**Comment by 6h4k5h498h9485gh39458h9o12um3412j34lj** [comment]
@krzysztofzablocki Here is the [sample](https://github.com/ivangoremykin/sourcery-issue), sorry for delay. Please run `pod install`. The steps to reproduce the issue are described in the ReadMe.

**Comment by Arasthel** [comment]
I don't know if this will make things easier, but I had this same issue with Xcode 10.2, in a project using Swift 4.2. Using `--disableCache` in fact, generates the files, but... not using the right template?

I'll elaborate a bit:

Before updating to 0.16.0 I had 2 swift templates that generated code for the project, let's call them **A** and **B**. Once I upgraded both Xcode and Sourcery, I tried adding a third one (**C**), which failed with the same error shown in this issue. I tried removing `~/Library/Caches/Sourcery` to no avail.

Then I tried the `--disableCache` arg. And the file got generated! But, and here's the 'funny' part, its contents were the same as the ones for the **A** template. So, in my YAML config file I switched from:

```yaml
templates:
    - Templates
```
And I did the follwing:

1. To manually stating the path for each template and I tried commenting out **A** and removing the `.generated.swift` files. This generated the file for template **C** again... looking exactly as the one generated for **B**. 
2. I commented out **B**, too, leaving only **C**, it still looked the same. 
3. I restored the config file to its previous state, deleted the `.generated.swift` files and... had the same results as before, the new file was a copy of the one generated for **A**.

So I have no clue what's exactly going on here, but it does look like some bug related to cache since my previous 2 templates can be generated just fine, and the generated file for the third is always a copy of one of theirs.

None of my templates use `arguments`, by the way.

**Comment by Arasthel** [comment]
I finally could get it to generate properly by fixing an issue on my template. Apparently, the swift code inside was at fault.

So I guess this means that any time the template has the wrong format and code can't be generated, this error will appear and the duplication issue seen with `--disableCache` will also happen.

**Comment by stephanecopin** [comment]
I think this issue is actually what I described in #758, so once it's merged this should be fixed (i.e. the proper error should be reported)

**Comment by strongSoda** [comment]
This error generally indicates that the system is unable to find a specific file or shortcut, likely because it has been moved, deleted, or is incorrectly linked.

Here’s how you can fix it:

- Confirm the File or Shortcut Exists: Check to ensure the file or shortcut you're trying to access is still in the correct location and hasn't been moved or deleted.
- Recreate the Shortcut: If the shortcut is broken, delete it and create a new one pointing to the correct file.
- Check File Permissions: Make sure you have the proper permissions to access the file by reviewing its settings.
- Restart your Mac: Rebooting your Mac can sometimes help resolve system-level issues causing this error.

[Step-by-step solutions and methods for macOS.](https://rref-calculator.com/blog/errordomain-nscocoaerrordomain-errormessage-could-not-find-the-specified-shortcut-errorcode-4/)
